# Generated by Django 4.2.26 on 2026-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_quicklessonrequest_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quicklessonmatch",
            name="student_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quicklessonmatch",
            name="tutor_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quicklessonmatch",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quicklessonmatch",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
