# Generated by Django 4.2.26 on 2026-05-26 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_add_point_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR (€)"),
                            ("USD", "USD ($)"),
                            ("CHF", "CHF (Fr.)"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wise", "Wise"),
                            ("paypal", "PayPal"),
                            ("bank", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        help_text="口座番号・PayPalメール・WiseメールなどをテキストでOK"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
