# Generated by Django 4.2.26 on 2026-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_withdrawal_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="last_ping_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
