# Generated by Django 4.2.26 on 2026-06-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_gold_subscription_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Stored as UTC internally. Django Admin shows it in the server timezone (Europe/Zurich)."
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Europe/Zurich", "Europe/Zurich (CET/CEST)"),
                            ("Asia/Tokyo", "Asia/Tokyo (JST)"),
                        ],
                        default="Asia/Tokyo",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("ja", "Japanese"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tutor_count", models.PositiveSmallIntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Upcoming Session",
                "verbose_name_plural": "Upcoming Sessions",
                "ordering": ["start_time"],
            },
        ),
    ]
