# Generated by Codex on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_online_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationnote",
            name="learner_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="conversationnote",
            name="talked_about",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="conversationnote",
            name="next_conversation",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
