# Generated by Django 4.2.26 on 2026-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tutorprofile_is_hourly_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationnote',
            name='questions_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='questions_level',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='questions_status',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='conversationnote',
            name='suggested_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
