# Generated by Django 4.2.26 on 2026-10-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_conversationnote_questions_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklessonmatch',
            name='student_private_note',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
